# moduals/__init__.py
__all__ = [
    "new_file",
    "open_file",
    "save_file",
    "save_as_file",
    "write_to_file",
    "toggle_topmost",
    "change_bg_color",
    "choose_custom_color",
    "new_window",
    "find_text",
    "open_replace_menu",
    "mark_as_modified",
    "schedule_spell_check",
    "check_spelling",
    "create_context_menu",
    "show_suggestions_menu",
    "replace_word",
    "adjust_font_size",
]
